package lab777;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


public class CourseBrowserFrame extends javax.swing.JDialog {
    private Student currentStudent;
    private List<Course> allCourses;
    private List<Course> filteredCourses;
    private JPanel coursesPanel;
    private JScrollPane scrollPane;

    /**
     * Creates new form CourseBrowserFrame
     */
    public CourseBrowserFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * New constructor with Student parameter
     */
    public CourseBrowserFrame(java.awt.Frame parent, boolean modal, Student student) {
        super(parent, modal);
        this.currentStudent = student;
        initComponents();
        initializeCourses();
        loadCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        allButton = new javax.swing.JToggleButton();
        programmingButton = new javax.swing.JToggleButton();
        mathButton = new javax.swing.JToggleButton();
        scienceButton = new javax.swing.JToggleButton();
        businessButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        advancedButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Course Browser");
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Course Browser");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        allButton.setSelected(true);
        allButton.setText("All");
        allButton.setFocusable(false);
        allButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        allButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        allButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(allButton);

        programmingButton.setText("Programming");
        programmingButton.setFocusable(false);
        programmingButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        programmingButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        programmingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programmingButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(programmingButton);

        mathButton.setText("Math");
        mathButton.setFocusable(false);
        mathButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mathButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(mathButton);

        scienceButton.setText("Science");
        scienceButton.setFocusable(false);
        scienceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scienceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        scienceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(scienceButton);

        businessButton.setText("Business");
        businessButton.setFocusable(false);
        businessButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        businessButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        businessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(businessButton);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Search:");

        searchField.setPreferredSize(new java.awt.Dimension(200, 30));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        advancedButton.setText("Advanced Filters");
        advancedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advancedButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(advancedButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void allButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        filterCoursesByCategory("All");
        updateButtonSelection(allButton);
    }                                         

    private void programmingButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        filterCoursesByCategory("Programming");
        updateButtonSelection(programmingButton);
    }                                                 

    private void mathButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        filterCoursesByCategory("Math");
        updateButtonSelection(mathButton);
    }                                          

    private void scienceButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        filterCoursesByCategory("Science");
        updateButtonSelection(scienceButton);
    }                                             

    private void businessButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        filterCoursesByCategory("Business");
        updateButtonSelection(businessButton);
    }                                              

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        searchCourses();
    }                                            

    private void advancedButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        JOptionPane.showMessageDialog(this, "Advanced filters feature coming soon!");
    }                                              

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {                                            
        searchCourses();
    }                                           

    /**
    * Initialize course data - FIXED VERSION FOR YOUR COURSE CLASS
    */
    private void initializeCourses() {
       allCourses = new ArrayList<>();

       // Sample courses - using YOUR Course constructor
       allCourses.add(new Course("CS101", "Java Basics", 
           "Learn Java fundamentals from basic syntax to object-oriented programming concepts. Perfect for beginners with no prior programming experience.", 
           "INST001"));

       allCourses.add(new Course("CS102", "Web Development 101", 
           "Build modern websites with HTML, CSS, and JavaScript. Learn responsive design and basic web development principles.", 
           "INST002"));

       allCourses.add(new Course("MATH201", "Calculus I", 
           "Introduction to differential and integral calculus. Topics include limits, derivatives, and applications of differentiation.", 
           "INST003"));

       allCourses.add(new Course("PHY101", "Physics Fundamentals", 
           "Basic principles of mechanics and thermodynamics. Explore motion, forces, energy, and heat transfer.", 
           "INST004"));

       allCourses.add(new Course("BUS101", "Business Management", 
           "Essential business principles and management strategies. Learn about organizational behavior, marketing, and finance basics.", 
           "INST005"));

       allCourses.add(new Course("CS201", "Data Structures", 
           "Advanced data structures and algorithms in Java. Covers arrays, linked lists, trees, graphs, and sorting algorithms.", 
           "INST006"));

       filteredCourses = new ArrayList<>(allCourses);
   }
    
    /**
     * Load courses into the UI
     */
    private void loadCourses() {
        // Create scroll pane and courses panel
        coursesPanel = new JPanel();
        coursesPanel.setLayout(new GridLayout(0, 3, 15, 15)); // 3 columns, 15px gaps
        coursesPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        coursesPanel.setBackground(Color.WHITE);
        
        scrollPane = new JScrollPane(coursesPanel);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
        mainPanel.add(scrollPane, BorderLayout.CENTER);
        
        refreshCourseCards();
    }
    
    /**
     * Refresh course cards display
     */
    private void refreshCourseCards() {
        coursesPanel.removeAll();
        
        for (Course course : filteredCourses) {
            JPanel courseCard = createCourseCard(course);
            coursesPanel.add(courseCard);
        }
        
        // Add empty panels to maintain layout if needed
        int remainingSlots = 3 - (filteredCourses.size() % 3);
        if (remainingSlots < 3 && filteredCourses.size() > 0) {
            for (int i = 0; i < remainingSlots; i++) {
                coursesPanel.add(new JPanel()); // Empty panel
            }
        }
        
        coursesPanel.revalidate();
        coursesPanel.repaint();
    }
    
    /**
     * Create individual course card
     */
    private JPanel createCourseCard(Course course) {
        JPanel card = new JPanel();
        card.setLayout(new BorderLayout(5, 5));
        card.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.LIGHT_GRAY),
            BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));
        card.setBackground(Color.WHITE);
        card.setPreferredSize(new Dimension(250, 220));
        
        // Course name
        JLabel nameLabel = new JLabel("<html><center>" + course.getCourseName() + "</center></html>");
        nameLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        nameLabel.setHorizontalAlignment(SwingConstants.CENTER);
        
        // Progress info - LINKED TO BACKEND
        boolean isEnrolled = currentStudent != null && currentStudent.isEnrolled(course.getCourseId());
        int completedLessons = isEnrolled ? currentStudent.getCompletedLessons(course.getCourseId()).size() : 0;
        int progress = course.getTotalLessons() > 0 ? (completedLessons * 100) / course.getTotalLessons() : 0;
        
        JPanel infoPanel = new JPanel();
        infoPanel.setLayout(new GridLayout(4, 1, 8, 8));
        infoPanel.setBackground(Color.WHITE);
        
        // Progress bar
        JProgressBar progressBar = new JProgressBar(0, 100);
        progressBar.setValue(progress);
        progressBar.setStringPainted(true);
        progressBar.setString(progress + "%");
        progressBar.setForeground(getProgressColor(progress));
        
        // Lessons info
        JLabel lessonsLabel = new JLabel("<html><center>" + completedLessons + "/" + course.getTotalLessons() + " lessons</center></html>");
        lessonsLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lessonsLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        
        // Instructor
        JLabel instructorLabel = new JLabel("<html><center>Instructor: " + course.getInstructor() + "</center></html>");
        instructorLabel.setHorizontalAlignment(SwingConstants.CENTER);
        instructorLabel.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        
        // Difficulty
        JLabel difficultyLabel = new JLabel("<html><center>Difficulty: " + getDifficultyStars(course.getDifficulty()) + "</center></html>");
        difficultyLabel.setHorizontalAlignment(SwingConstants.CENTER);
        difficultyLabel.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        
        infoPanel.add(progressBar);
        infoPanel.add(lessonsLabel);
        infoPanel.add(instructorLabel);
        infoPanel.add(difficultyLabel);
        
        // Action button - LINKED TO BACKEND
        JButton actionButton = new JButton();
        actionButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        
        if (isEnrolled) {
            if (progress == 100) {
                actionButton.setText("View Details");
                actionButton.setBackground(new Color(76, 175, 80)); // Green
            } else if (progress > 0) {
                actionButton.setText("Continue");
                actionButton.setBackground(new Color(255, 152, 0)); // Orange
            } else {
                actionButton.setText("Start Learning");
                actionButton.setBackground(new Color(33, 150, 243)); // Blue
            }
            //actionButton.addActionListener(e -> showCourseDetailsDialog(course));
            
                actionButton.addActionListener(e -> {
                System.out.println("Course card clicked: " + course.getCourseName());
                System.out.println("Calling showCourseDetailsDialog...");
                try {
                showCourseDetailsDialog(course);
                System.out.println("showCourseDetailsDialog completed");
                } catch (Exception ex) {
                System.out.println("Error in showCourseDetailsDialog: " + ex.getMessage());
                ex.printStackTrace();
    }
});
        } else {
            actionButton.setText("Enroll Now");
            actionButton.setBackground(new Color(156, 39, 176)); // Purple
            actionButton.addActionListener(e -> handleEnrollment(course));
        }
        
        actionButton.setForeground(Color.WHITE);
        actionButton.setFocusPainted(false);
        
        // Add components to card
        card.add(nameLabel, BorderLayout.NORTH);
        card.add(infoPanel, BorderLayout.CENTER);
        card.add(actionButton, BorderLayout.SOUTH);
        
        return card;
    }
    
    /**
     * Get color based on progress percentage
     */
    private Color getProgressColor(int progress) {
        if (progress < 30) return new Color(244, 67, 54); // Red
        if (progress < 70) return new Color(255, 152, 0); // Orange
        return new Color(76, 175, 80); // Green
    }
    
    /**
     * Get difficulty as stars
     */
    private String getDifficultyStars(String difficulty) {
        switch (difficulty.toLowerCase()) {
            case "beginner": return "⭐";
            case "intermediate": return "⭐⭐";
            case "advanced": return "⭐⭐⭐";
            default: return "⭐";
        }
    }
    
    /**
     * Handle course enrollment
     */
    private void handleEnrollment(Course course) {
        int response = JOptionPane.showConfirmDialog(this,
            "<html>Enroll in <b>" + course.getCourseName() + "</b>?<br><br>" +
            "Instructor: " + course.getInstructor() + "<br>" +
            "Duration: " + course.getTotalLessons() + " lessons<br>" +
            "Difficulty: " + course.getDifficulty() + "</html>",
            "Enroll in Course",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION) {
            if (currentStudent.enrollCourse(course.getCourseId())) {
                JOptionPane.showMessageDialog(this, 
                    "<html><b>Successfully enrolled!</b><br><br>" +
                    "You are now enrolled in: " + course.getCourseName() + "<br>" +
                    "Start your learning journey!</html>", 
                    "Enrollment Successful", 
                    JOptionPane.INFORMATION_MESSAGE);
                refreshCourseCards();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "You are already enrolled in this course!", 
                    "Already Enrolled", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
    /**
     * COURSE DETAILS DIALOG: Show detailed course information
     */
    private void showCourseDetailsDialog(Course course) {
        // Create the dialog
        JDialog detailsDialog = new JDialog(this, "Course Details", true);
        detailsDialog.setLayout(new BorderLayout());
        detailsDialog.setSize(550, 600);
        detailsDialog.setLocationRelativeTo(this);
        
        // Main content panel
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(15, 15));
        contentPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        // ===== TITLE SECTION =====
        JLabel titleLabel = new JLabel(course.getCourseName(), JLabel.CENTER);
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
        titleLabel.setForeground(new Color(33, 150, 243));
        
        // ===== COURSE INFO SECTION =====
        JPanel infoPanel = new JPanel(new GridLayout(5, 2, 10, 10));
        infoPanel.setBorder(BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(Color.LIGHT_GRAY), "Course Information"));
        
        // Get student-specific data from backend
        boolean isEnrolled = currentStudent.isEnrolled(course.getCourseId());
        List<String> completedLessons = currentStudent.getCompletedLessons(course.getCourseId());
        int progress = isEnrolled ? (completedLessons.size() * 100) / course.getTotalLessons() : 0;
        
        infoPanel.add(createInfoLabel("Course ID:"));
        infoPanel.add(createInfoValue(course.getCourseId()));
        
        infoPanel.add(createInfoLabel("Instructor:"));
        infoPanel.add(createInfoValue(course.getInstructor()));
        
        infoPanel.add(createInfoLabel("Category:"));
        infoPanel.add(createInfoValue(course.getCategory()));
        
        infoPanel.add(createInfoLabel("Difficulty:"));
        infoPanel.add(createInfoValue(course.getDifficulty() + " " + getDifficultyStars(course.getDifficulty())));
        
        infoPanel.add(createInfoLabel("Your Progress:"));
        infoPanel.add(createInfoValue(progress + "% (" + completedLessons.size() + "/" + course.getTotalLessons() + " lessons)"));
        
        // ===== PROGRESS BAR =====
        JProgressBar progressBar = new JProgressBar(0, 100);
        progressBar.setValue(progress);
        progressBar.setStringPainted(true);
        progressBar.setString(progress + "% Complete");
        progressBar.setForeground(getProgressColor(progress));
        progressBar.setFont(new Font("Segoe UI", Font.BOLD, 12));
        progressBar.setPreferredSize(new Dimension(400, 25));
        
        // ===== DESCRIPTION SECTION =====
        JTextArea descriptionArea = new JTextArea(course.getDescription());
        descriptionArea.setLineWrap(true);
        descriptionArea.setWrapStyleWord(true);
        descriptionArea.setEditable(false);
        descriptionArea.setBackground(new Color(248, 248, 248));
        descriptionArea.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        descriptionArea.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        JScrollPane descriptionScroll = new JScrollPane(descriptionArea);
        descriptionScroll.setBorder(BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(Color.LIGHT_GRAY), "Course Description"));
        descriptionScroll.setPreferredSize(new Dimension(400, 100));
        
        // ===== LESSONS SECTION =====
        JPanel lessonsPanel = new JPanel(new BorderLayout());
        lessonsPanel.setBorder(BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(Color.LIGHT_GRAY), "Course Lessons"));
        
        // Create lessons list based on student progress
        DefaultListModel<String> lessonsModel = new DefaultListModel<>();
        
        // Generate lesson list
        for (int i = 1; i <= course.getTotalLessons(); i++) {
            String lessonId = "L" + i;
            String lessonName = "Lesson " + i + ": " + getLessonTitle(course.getCourseId(), i);
            boolean isCompleted = completedLessons.contains(lessonId);
            
            String statusIcon = isCompleted ? "✓ " : "○ ";
            String statusText = isCompleted ? " - Completed" : " - Not Started";
            Color statusColor = isCompleted ? new Color(76, 175, 80) : Color.GRAY;
            
            lessonsModel.addElement("<html>" + statusIcon + "<font color='black'>" + lessonName + "</font><font color='" + 
                                  String.format("#%02x%02x%02x", statusColor.getRed(), statusColor.getGreen(), statusColor.getBlue()) + 
                                  "'>" + statusText + "</font></html>");
        }
        
        JList<String> lessonsList = new JList<>(lessonsModel);
        lessonsList.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lessonsList.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                label.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
                return label;
            }
        });
        
        JScrollPane lessonsScroll = new JScrollPane(lessonsList);
        lessonsScroll.setPreferredSize(new Dimension(400, 150));
        
        lessonsPanel.add(lessonsScroll, BorderLayout.CENTER);
        
        // ===== ACTION BUTTONS =====
        JPanel buttonPanel = new JPanel(new FlowLayout());
        buttonPanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0));
        
        JButton startButton = new JButton();
        startButton.setFont(new Font("Segoe UI", Font.BOLD, 14));
        startButton.setForeground(Color.WHITE);
        startButton.setFocusPainted(false);
        
        if (progress == 100) {
            startButton.setText("Review Course");
            startButton.setBackground(new Color(76, 175, 80)); // Green
        } else if (progress > 0) {
            startButton.setText("Continue Learning");
            startButton.setBackground(new Color(255, 152, 0)); // Orange
        } else {
            startButton.setText("Start Learning");
            startButton.setBackground(new Color(33, 150, 243)); // Blue
        }
        
        startButton.addActionListener(e -> {
            startCourseLearning(course);
            detailsDialog.dispose();
        });
        
        JButton closeButton = new JButton("Close");
        closeButton.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        closeButton.addActionListener(e -> detailsDialog.dispose());
        
        buttonPanel.add(startButton);
        buttonPanel.add(Box.createHorizontalStrut(20));
        buttonPanel.add(closeButton);
        
        // ===== ASSEMBLE DIALOG =====
        contentPanel.add(titleLabel, BorderLayout.NORTH);
        
        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
        centerPanel.add(infoPanel);
        centerPanel.add(Box.createVerticalStrut(15));
        centerPanel.add(progressBar);
        centerPanel.add(Box.createVerticalStrut(15));
        centerPanel.add(descriptionScroll);
        centerPanel.add(Box.createVerticalStrut(15));
        centerPanel.add(lessonsPanel);
        
        contentPanel.add(centerPanel, BorderLayout.CENTER);
        contentPanel.add(buttonPanel, BorderLayout.SOUTH);
        
        detailsDialog.add(contentPanel);
        detailsDialog.setVisible(true);
    }
    
    /**
     * Helper method to create info labels
     */
    private JLabel createInfoLabel(String text) {
        JLabel label = new JLabel(text);
        label.setFont(new Font("Segoe UI", Font.BOLD, 12));
        return label;
    }
    
    /**
     * Helper method to create info values
     */
    private JLabel createInfoValue(String text) {
        JLabel label = new JLabel(text);
        label.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        return label;
    }
    
    /**
     * Helper method to get lesson titles
     */
    private String getLessonTitle(String courseId, int lessonNumber) {
        Map<String, String[]> lessonTitles = new HashMap<>();
        lessonTitles.put("CS101", new String[]{
            "Introduction to Java", "Variables and Data Types", "Control Structures", 
            "Methods and Functions", "Object-Oriented Programming", "Arrays and Collections",
            "Exception Handling", "File I/O", "GUI Basics", "Final Project"
        });
        lessonTitles.put("CS102", new String[]{
            "HTML Fundamentals", "CSS Styling", "JavaScript Basics",
            "DOM Manipulation", "Responsive Design", "Web Forms",
            "APIs and AJAX", "Web Security", "Project Setup", "Debugging",
            "Deployment", "Final Project"
        });
        lessonTitles.put("MATH201", new String[]{
            "Limits and Continuity", "Derivatives", "Applications of Derivatives",
            "Integration", "Definite Integrals", "Applications of Integration",
            "Transcendental Functions", "Integration Techniques", "Differential Equations",
            "Sequences and Series", "Power Series", "Parametric Equations",
            "Polar Coordinates", "Vector Functions", "Partial Derivatives"
        });
        lessonTitles.put("PHY101", new String[]{
            "Motion in One Dimension", "Vectors and Motion in 2D", "Forces and Newton's Laws",
            "Work and Energy", "Momentum and Collisions", "Rotational Motion",
            "Gravitation", "Fluid Mechanics", "Oscillations", "Waves",
            "Thermodynamics", "Heat Transfer", "Kinetic Theory", "Entropy"
        });
        lessonTitles.put("BUS101", new String[]{
            "Introduction to Business", "Management Principles", "Organizational Behavior",
            "Marketing Fundamentals", "Financial Accounting", "Business Ethics",
            "Operations Management", "Human Resources", "Strategic Planning", "Entrepreneurship"
        });
        lessonTitles.put("CS201", new String[]{
            "Algorithm Analysis", "Arrays and ArrayLists", "Linked Lists",
            "Stacks and Queues", "Trees and Binary Search Trees", "Heaps and Priority Queues",
            "Hash Tables", "Graphs and Graph Algorithms", "Sorting Algorithms",
            "Searching Algorithms", "Recursion", "Dynamic Programming",
            "Greedy Algorithms", "Algorithm Design Patterns", "Complexity Theory", "Review and Projects"
        });
        
        String[] titles = lessonTitles.get(courseId);
        if (titles != null && lessonNumber <= titles.length) {
            return titles[lessonNumber - 1];
        }
        return "Topic " + lessonNumber;
    }
    
    /**
     * LINKING: Start or continue course learning
     */
    private void startCourseLearning(Course course) {
        // Get the next uncompleted lesson
        List<String> completedLessons = currentStudent.getCompletedLessons(course.getCourseId());
        int nextLesson = completedLessons.size() + 1;
        
        if (nextLesson <= course.getTotalLessons()) {
            String lessonId = "L" + nextLesson;
            String lessonTitle = getLessonTitle(course.getCourseId(), nextLesson);
            
            int response = JOptionPane.showConfirmDialog(this,
                "<html><b>Start Lesson " + nextLesson + "</b><br><br>" +
                "Course: " + course.getCourseName() + "<br>" +
                "Lesson: " + lessonTitle + "<br><br>" +
                "Mark this lesson as completed?</html>",
                "Start Learning",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            
            if (response == JOptionPane.YES_OPTION) {
                // Update backend
                currentStudent.markLessonCompleted(course.getCourseId(), lessonId);
                
                // Refresh frontend
                refreshCourseCards();
                
                JOptionPane.showMessageDialog(this,
                    "<html><b>Lesson Completed!</b><br><br>" +
                    "You have completed: " + lessonTitle + "<br>" +
                    "Keep up the great work!</html>",
                    "Progress Updated",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                "<html><b>Congratulations!</b><br><br>" +
                "You've successfully completed:<br>" +
                "<b>" + course.getCourseName() + "</b><br><br>" +
                "All " + course.getTotalLessons() + " lessons are now complete!</html>",
                "Course Completed",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * Filter courses by category
     */
    private void filterCoursesByCategory(String category) {
        if (category.equals("All")) {
            filteredCourses = new ArrayList<>(allCourses);
        } else {
            filteredCourses = new ArrayList<>();
            for (Course course : allCourses) {
                if (course.getCategory().equals(category)) {
                    filteredCourses.add(course);
                }
            }
        }
        refreshCourseCards();
    }
    
    /**
     * Update button selection state
     */
    private void updateButtonSelection(JToggleButton selectedButton) {
        allButton.setSelected(selectedButton == allButton);
        programmingButton.setSelected(selectedButton == programmingButton);
        mathButton.setSelected(selectedButton == mathButton);
        scienceButton.setSelected(selectedButton == scienceButton);
        businessButton.setSelected(selectedButton == businessButton);
    }
    
    /**
     * Search courses
     */
    private void searchCourses() {
        String searchText = searchField.getText().toLowerCase().trim();
        
        if (searchText.isEmpty()) {
            filteredCourses = new ArrayList<>(allCourses);
        } else {
            filteredCourses = new ArrayList<>();
            for (Course course : allCourses) {
                if (course.getCourseName().toLowerCase().contains(searchText) ||
                    course.getInstructor().toLowerCase().contains(searchText) ||
                    course.getDescription().toLowerCase().contains(searchText) ||
                    course.getCategory().toLowerCase().contains(searchText)) {
                    filteredCourses.add(course);
                }
            }
        }
        refreshCourseCards();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseBrowserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseBrowserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseBrowserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseBrowserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Create a sample student for testing
                Student sampleStudent = new Student("STU001", "john_doe", "john@student.com", "password123");
                sampleStudent.enrollCourse("CS101");
                sampleStudent.markLessonCompleted("CS101", "L1");
                sampleStudent.markLessonCompleted("CS101", "L2");
                sampleStudent.markLessonCompleted("CS101", "L3");
                
                CourseBrowserFrame dialog = new CourseBrowserFrame(new javax.swing.JFrame(), true, sampleStudent);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton allButton;
    private javax.swing.JButton advancedButton;
    private javax.swing.JToggleButton businessButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JToggleButton mathButton;
    private javax.swing.JToggleButton programmingButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JToggleButton scienceButton;
    // End of variables declaration                   
}
